export const listTools = [
  {
    id: 1,
    gambar: "/assets/tools/laravel.png",
    nama: "Laravel",
    ket: "Framework",
    dad: "100",
  },
  {
    id: 2,
    gambar: "/assets/tools/flutter.png",
    nama: "Flutter",
    ket: "Framework",
    dad: "200",
  },
  {
    id: 3,
    gambar: "/assets/tools/dart.png",
    nama: "Dart",
    ket: "Programming Lenguage",
    dad: "300",
  },
  {
    id: 4,
    gambar: "/assets/tools/bootstrap.png",
    nama: "Bootstrap",
    ket: "Framework",
    dad: "400",
  },
  {
    id: 5,
    gambar: "/assets/tools/tailwind.png",
    nama: "Tailwind CSS",
    ket: "Framework",
    dad: "500",
  },
  {
    id: 6,
    gambar: "/assets/tools/js.png",
    nama: "Javascript",
    ket: "Language",
    dad: "600",
  },
  {
    id: 7,
    gambar: "/assets/tools/nextjs.png",
    nama: "Next JS",
    ket: "Javascript Runtime",
    dad: "700",
  },
  {
    id: 8,
    gambar: "/assets/tools/reactjs.png",
    nama: "React JS",
    ket: "Repository",
    dad: "800",
  },
  {
    id: 9,
    gambar: "/assets/tools/mysql.png",
    nama: "My SQL",
    ket: "Design App",
    dad: "900",
  },
  {
    id: 10,
    gambar: "/assets/tools/cLanguage.png",
    nama: "C",
    ket: "Design App",
    dad: "1000",
  },
];